services:
  heyform:
    image: 'heyform/community-edition:latest'
    volumes:
      - 'heyform-assets:/app/static/upload'
    depends_on:
      mongo:
        condition: service_healthy
      keydb:
        condition: service_healthy
    environment:
      - SERVICE_FQDN_HEYFORM_8000
      - 'APP_HOMEPAGE_URL=${SERVICE_FQDN_HEYFORM_8000}' # 修正：更改為使用 SERVICE_FQDN_HEYFORM_8000
      - 'SESSION_KEY=${SERVICE_BASE64_64_SESSION}'
      - 'FORM_ENCRYPTION_KEY=${SERVICE_BASE64_64_FORM}'
      - 'MONGO_URI=mongodb://pukpuk:gatsby11@mongo:27017/heyform?authSource=admin'
      - REDIS_HOST=keydb
      - REDIS_PORT=6379
      - 'REDIS_PASSWORD=${SERVICE_PASSWORD_KEYDB}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:8000 || exit 1'
      interval: 5s
      timeout: 5s
      retries: 3
  mongo:
    image: percona/percona-server-mongodb:8.0.8-3-arm64
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: pukpuk
      MONGO_INITDB_ROOT_PASSWORD: gatsby11
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
  keydb:
    image: 'eqalpha/keydb:latest'
    command: 'keydb-server --appendonly yes'
    environment:
      - 'KEYDB_PASSWORD=${SERVICE_PASSWORD_KEYDB}'
    volumes:
      - 'heyform-keydb-data:/data'
    healthcheck:
      test:
        - CMD-SHELL
        - keydb-cli
        - '--pass'
        - '${SERVICE_PASSWORD_KEYDB}'
        - ping
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
      
