name: Docker Image Build and push to GHCR.io Action

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Checkout mongodb-raspberrypi-docker repository
        uses: actions/checkout@v3
        with:
          repository: themattman/mongodb-raspberrypi-docker
          ref: main
          path: mongodb-raspberrypi-docker

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/mongodb-raspberrypi-docker
          IMAGE_TAG=r7.0.14
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f mongodb-raspberrypi-docker/7.0.14/Dockerfile mongodb-raspberrypi-docker/7.0.14

      - name: Push image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/mongodb-raspberrypi-docker
          IMAGE_TAG=r7.0.14
          docker push $IMAGE_NAME:$IMAGE_TAG